EnglishTranslation/Controllers/NewsDetailController.cs
using System.Web.Mvc;

namespace EnglishTranslation.Controllers
{
    public class NewsDetailController : Controller
    {
        // GET: NewsDetail
        public ActionResult Index()
        {
            return View();
        }
    }
}

EnglishTranslation/Views/NewsDetail/Index.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<div class="main_bg">
    <div class="wrap">
        <div class="wrapper">
            <div class="main">
                <div class="details">
                    <h2 class="style">Lorem ipsum dolor sit amet consectetur incididunt</h2>
                    <div class="det_pic img_style">
                        <img src="~/images/det-pic.jpg" alt="">		
                    </div>
                    <div class="det-para">
                        <p class="top para">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor</p>
                        <div class="button1">
                            <a href="@Url.Action("Index", "NewsDetail")" class="btn btn_s">view More</a>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>